// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nesto.Models;

namespace nesto.Migrations
{
    [DbContext(typeof(PicerijaContext))]
    [Migration("20210317181744_V1")]
    partial class V1
    {
      
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("nesto.Models.Picerija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<int>("M")
                        .HasColumnType("int")
                        .HasColumnName("M");

                    b.Property<int>("N")
                        .HasColumnType("int")
                        .HasColumnName("N");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Picerija");
                });

            modelBuilder.Entity("nesto.Models.Stolovi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImeRezervacije")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ImeRezervacije");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("MaxKapacitet");

                    b.Property<int?>("PicerijaID")
                        .HasColumnType("int");

                    b.Property<string>("Pusac")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Pusac");

                    b.Property<int>("S")
                        .HasColumnType("int")
                        .HasColumnName("S");

                    b.HasKey("ID");

                    b.HasIndex("PicerijaID");

                    b.ToTable("Stolovi");
                });

            modelBuilder.Entity("nesto.Models.Stolovi", b =>
                {
                    b.HasOne("nesto.Models.Picerija", "Picerija")
                        .WithMany("Stolovii")
                        .HasForeignKey("PicerijaID");

                    b.Navigation("Picerija");
                });

            modelBuilder.Entity("nesto.Models.Picerija", b =>
                {
                    b.Navigation("Stolovii");
                });
#pragma warning restore 612, 618
        }
    }
}
